### ISSUE TITLE
Save to tmp file without refreshing tmux

### ISSUE THREAD

**Issue by wandy-dev** [connermcd/gtd#7]
So I use polybar which allows bash script outputs to be displayed in a status bar, so just using cat to display the contents of the tmp file would be extremely useful, but I don't necessarily want the tmux functionality.

If you don't have tmux running when you specify the -t flag, it prints an error every second to standard out. This makes the output of the script pretty ugly.

I'd like to add a -T flag for the ability to output to a tmp file with no tmux functionality.

I noticed this project is pretty inactive so just let me know if you're still merging PR's thanks!

**Comment by connermcd** [comment]
Hey thanks for the interest. I'd be happy to find a compromise. I'd love a way to make the tmux flag more broadly applicable in general. The issue I ran into was that the tmux client doesn't refresh the time unless you tell it to, but I suppose that's more of tmux's problem than this scripts. I'd be happy to entertain/accept a PR.

**Comment by wandy-dev** [comment]
So I was thinking we could have the part of the script that outputs the tmpfile run on -t or -T

`$DO_TMUX || $DO_TMP_FILE`

But the tmux refresh would only run on -t. 

`$DO_TMUX`

This would allow for tmux refresh for those who want it, and tmp file output for those who just want to handle it on their own.
